/**
 * words.js
 * 全単語データ。グローバル変数 QuizWords として公開。
 */

var QuizWords = (function () {

  var POS = {
    verb:      { ja: '動詞',   en: 'Verb' },
    noun:      { ja: '名詞',   en: 'Noun' },
    adjective: { ja: '形容詞', en: 'Adj.' },
    adverb:    { ja: '副詞',   en: 'Adv.' },
  };

  var CHOICES = ['verb', 'noun', 'adjective', 'adverb'];

  var REGULAR_WORDS = [
    // NOUNS: -tion
    { word: 'education',      suffix: '-tion', pos: 'noun', ja: '教育' },
    { word: 'information',    suffix: '-tion', pos: 'noun', ja: '情報' },
    { word: 'attention',      suffix: '-tion', pos: 'noun', ja: '注意' },
    { word: 'solution',       suffix: '-tion', pos: 'noun', ja: '解決策' },
    { word: 'production',     suffix: '-tion', pos: 'noun', ja: '生産' },
    { word: 'situation',      suffix: '-tion', pos: 'noun', ja: '状況' },
    { word: 'communication',  suffix: '-tion', pos: 'noun', ja: '意思疎通' },
    { word: 'organization',   suffix: '-tion', pos: 'noun', ja: '組織' },
    { word: 'motivation',     suffix: '-tion', pos: 'noun', ja: '動機付け' },
    { word: 'transportation', suffix: '-tion', pos: 'noun', ja: '輸送' },
    { word: 'examination',    suffix: '-tion', pos: 'noun', ja: '試験' },
    { word: 'introduction',   suffix: '-tion', pos: 'noun', ja: '紹介' },
    { word: 'population',     suffix: '-tion', pos: 'noun', ja: '人口' },
    { word: 'foundation',     suffix: '-tion', pos: 'noun', ja: '基盤' },
    { word: 'recommendation', suffix: '-tion', pos: 'noun', ja: '推薦' },
    // NOUNS: -ment
    { word: 'management',   suffix: '-ment', pos: 'noun', ja: '管理' },
    { word: 'agreement',    suffix: '-ment', pos: 'noun', ja: '合意' },
    { word: 'achievement',  suffix: '-ment', pos: 'noun', ja: '達成' },
    { word: 'improvement',  suffix: '-ment', pos: 'noun', ja: '改善' },
    { word: 'development',  suffix: '-ment', pos: 'noun', ja: '発展' },
    { word: 'environment',  suffix: '-ment', pos: 'noun', ja: '環境' },
    { word: 'requirement',  suffix: '-ment', pos: 'noun', ja: '要件' },
    { word: 'appointment',  suffix: '-ment', pos: 'noun', ja: '予約・任命' },
    { word: 'investment',   suffix: '-ment', pos: 'noun', ja: '投資' },
    { word: 'assessment',   suffix: '-ment', pos: 'noun', ja: '評価' },
    { word: 'announcement', suffix: '-ment', pos: 'noun', ja: '発表' },
    { word: 'department',   suffix: '-ment', pos: 'noun', ja: '部門' },
    // NOUNS: -ness
    { word: 'happiness',  suffix: '-ness', pos: 'noun', ja: '幸福' },
    { word: 'awareness',  suffix: '-ness', pos: 'noun', ja: '認識・意識' },
    { word: 'weakness',   suffix: '-ness', pos: 'noun', ja: '弱点' },
    { word: 'darkness',   suffix: '-ness', pos: 'noun', ja: '暗さ' },
    { word: 'kindness',   suffix: '-ness', pos: 'noun', ja: '親切' },
    { word: 'illness',    suffix: '-ness', pos: 'noun', ja: '病気' },
    { word: 'fitness',    suffix: '-ness', pos: 'noun', ja: '健康' },
    { word: 'fairness',   suffix: '-ness', pos: 'noun', ja: '公平さ' },
    { word: 'loneliness', suffix: '-ness', pos: 'noun', ja: '孤独' },
    { word: 'readiness',  suffix: '-ness', pos: 'noun', ja: '準備完了' },
    // NOUNS: -ity
    { word: 'ability',        suffix: '-ity', pos: 'noun', ja: '能力' },
    { word: 'activity',       suffix: '-ity', pos: 'noun', ja: '活動' },
    { word: 'opportunity',    suffix: '-ity', pos: 'noun', ja: '機会' },
    { word: 'responsibility', suffix: '-ity', pos: 'noun', ja: '責任' },
    { word: 'creativity',     suffix: '-ity', pos: 'noun', ja: '創造性' },
    { word: 'possibility',    suffix: '-ity', pos: 'noun', ja: '可能性' },
    { word: 'quality',        suffix: '-ity', pos: 'noun', ja: '品質' },
    { word: 'community',      suffix: '-ity', pos: 'noun', ja: '地域社会' },
    { word: 'security',       suffix: '-ity', pos: 'noun', ja: '安全' },
    { word: 'priority',       suffix: '-ity', pos: 'noun', ja: '優先事項' },
    { word: 'diversity',      suffix: '-ity', pos: 'noun', ja: '多様性' },
    { word: 'flexibility',    suffix: '-ity', pos: 'noun', ja: '柔軟性' },
    // NOUNS: -ance / -ence
    { word: 'performance',  suffix: '-ance', pos: 'noun', ja: '実績' },
    { word: 'importance',   suffix: '-ance', pos: 'noun', ja: '重要性' },
    { word: 'balance',      suffix: '-ance', pos: 'noun', ja: 'バランス' },
    { word: 'evidence',     suffix: '-ence', pos: 'noun', ja: '証拠' },
    { word: 'difference',   suffix: '-ence', pos: 'noun', ja: '違い' },
    { word: 'experience',   suffix: '-ence', pos: 'noun', ja: '経験' },
    { word: 'conference',   suffix: '-ence', pos: 'noun', ja: '会議' },
    { word: 'confidence',   suffix: '-ence', pos: 'noun', ja: '自信' },
    { word: 'independence', suffix: '-ence', pos: 'noun', ja: '独立' },
    { word: 'influence',    suffix: '-ence', pos: 'noun', ja: '影響' },
    // NOUNS: -ion
    { word: 'decision',   suffix: '-ion', pos: 'noun', ja: '決断' },
    { word: 'discussion', suffix: '-ion', pos: 'noun', ja: '議論' },
    { word: 'permission', suffix: '-ion', pos: 'noun', ja: '許可' },
    { word: 'expression', suffix: '-ion', pos: 'noun', ja: '表現' },
    { word: 'impression', suffix: '-ion', pos: 'noun', ja: '印象' },
    { word: 'tension',    suffix: '-ion', pos: 'noun', ja: '緊張' },
    { word: 'passion',    suffix: '-ion', pos: 'noun', ja: '情熱' },
    // NOUNS: -cy
    { word: 'agency',     suffix: '-cy', pos: 'noun', ja: '代理店' },
    { word: 'policy',     suffix: '-cy', pos: 'noun', ja: '方針' },
    { word: 'efficiency', suffix: '-cy', pos: 'noun', ja: '効率' },
    { word: 'accuracy',   suffix: '-cy', pos: 'noun', ja: '正確さ' },
    { word: 'currency',   suffix: '-cy', pos: 'noun', ja: '通貨' },
    { word: 'frequency',  suffix: '-cy', pos: 'noun', ja: '頻度' },
    { word: 'urgency',    suffix: '-cy', pos: 'noun', ja: '緊急性' },
    { word: 'democracy',  suffix: '-cy', pos: 'noun', ja: '民主主義' },
    { word: 'literacy',   suffix: '-cy', pos: 'noun', ja: '読み書き能力' },
    { word: 'tendency',   suffix: '-cy', pos: 'noun', ja: '傾向' },
    // NOUNS: -th
    { word: 'growth',   suffix: '-th', pos: 'noun', ja: '成長' },
    { word: 'length',   suffix: '-th', pos: 'noun', ja: '長さ' },
    { word: 'strength', suffix: '-th', pos: 'noun', ja: '強さ' },
    { word: 'health',   suffix: '-th', pos: 'noun', ja: '健康' },
    { word: 'wealth',   suffix: '-th', pos: 'noun', ja: '富' },
    { word: 'depth',    suffix: '-th', pos: 'noun', ja: '深さ' },
    { word: 'warmth',   suffix: '-th', pos: 'noun', ja: '温かさ' },
    { word: 'youth',    suffix: '-th', pos: 'noun', ja: '若さ・青年期' },
    { word: 'truth',    suffix: '-th', pos: 'noun', ja: '真実' },
    // NOUNS: -er / -or
    { word: 'consumer',   suffix: '-er', pos: 'noun', ja: '消費者' },
    { word: 'employer',   suffix: '-er', pos: 'noun', ja: '雇用者' },
    { word: 'supplier',   suffix: '-er', pos: 'noun', ja: '供給業者' },
    { word: 'researcher', suffix: '-er', pos: 'noun', ja: '研究者' },
    { word: 'customer',   suffix: '-er', pos: 'noun', ja: '顧客' },
    { word: 'manager',    suffix: '-er', pos: 'noun', ja: '管理者' },
    { word: 'leader',     suffix: '-er', pos: 'noun', ja: 'リーダー' },
    { word: 'investor',   suffix: '-or', pos: 'noun', ja: '投資家' },
    { word: 'supervisor', suffix: '-or', pos: 'noun', ja: '監督者' },
    { word: 'competitor', suffix: '-or', pos: 'noun', ja: '競合他社' },
    // VERBS: -ate
    { word: 'calculate',   suffix: '-ate', pos: 'verb', ja: '計算する' },
    { word: 'operate',     suffix: '-ate', pos: 'verb', ja: '操作する' },
    { word: 'communicate', suffix: '-ate', pos: 'verb', ja: '伝達する' },
    { word: 'participate', suffix: '-ate', pos: 'verb', ja: '参加する' },
    { word: 'investigate', suffix: '-ate', pos: 'verb', ja: '調査する' },
    { word: 'demonstrate', suffix: '-ate', pos: 'verb', ja: '実演する' },
    { word: 'negotiate',   suffix: '-ate', pos: 'verb', ja: '交渉する' },
    { word: 'evaluate',    suffix: '-ate', pos: 'verb', ja: '評価する' },
    { word: 'motivate',    suffix: '-ate', pos: 'verb', ja: '動機付ける' },
    { word: 'generate',    suffix: '-ate', pos: 'verb', ja: '生み出す' },
    { word: 'translate',   suffix: '-ate', pos: 'verb', ja: '翻訳する' },
    { word: 'appreciate',  suffix: '-ate', pos: 'verb', ja: '感謝する' },
    { word: 'coordinate',  suffix: '-ate', pos: 'verb', ja: '調整する' },
    { word: 'allocate',    suffix: '-ate', pos: 'verb', ja: '割り当てる' },
    // VERBS: -ify
    { word: 'clarify',  suffix: '-ify', pos: 'verb', ja: '明確にする' },
    { word: 'identify', suffix: '-ify', pos: 'verb', ja: '特定する' },
    { word: 'simplify', suffix: '-ify', pos: 'verb', ja: '単純化する' },
    { word: 'qualify',  suffix: '-ify', pos: 'verb', ja: '資格を得る' },
    { word: 'modify',   suffix: '-ify', pos: 'verb', ja: '変更する' },
    { word: 'notify',   suffix: '-ify', pos: 'verb', ja: '通知する' },
    { word: 'justify',  suffix: '-ify', pos: 'verb', ja: '正当化する' },
    { word: 'verify',   suffix: '-ify', pos: 'verb', ja: '確認する' },
    { word: 'classify', suffix: '-ify', pos: 'verb', ja: '分類する' },
    { word: 'satisfy',  suffix: '-ify', pos: 'verb', ja: '満足させる' },
    // VERBS: -ize
    { word: 'organize',    suffix: '-ize', pos: 'verb', ja: '組織する' },
    { word: 'realize',     suffix: '-ize', pos: 'verb', ja: '気づく' },
    { word: 'recognize',   suffix: '-ize', pos: 'verb', ja: '認識する' },
    { word: 'summarize',   suffix: '-ize', pos: 'verb', ja: '要約する' },
    { word: 'prioritize',  suffix: '-ize', pos: 'verb', ja: '優先する' },
    { word: 'analyze',     suffix: '-ize', pos: 'verb', ja: '分析する' },
    { word: 'maximize',    suffix: '-ize', pos: 'verb', ja: '最大化する' },
    { word: 'minimize',    suffix: '-ize', pos: 'verb', ja: '最小化する' },
    { word: 'emphasize',   suffix: '-ize', pos: 'verb', ja: '強調する' },
    { word: 'optimize',    suffix: '-ize', pos: 'verb', ja: '最適化する' },
    { word: 'utilize',     suffix: '-ize', pos: 'verb', ja: '活用する' },
    { word: 'standardize', suffix: '-ize', pos: 'verb', ja: '標準化する' },
    // VERBS: -en
    { word: 'strengthen', suffix: '-en', pos: 'verb', ja: '強化する' },
    { word: 'broaden',    suffix: '-en', pos: 'verb', ja: '広げる' },
    { word: 'frighten',   suffix: '-en', pos: 'verb', ja: '怖がらせる' },
    { word: 'sharpen',    suffix: '-en', pos: 'verb', ja: '鋭くする' },
    { word: 'widen',      suffix: '-en', pos: 'verb', ja: '広くする' },
    { word: 'deepen',     suffix: '-en', pos: 'verb', ja: '深める' },
    { word: 'loosen',     suffix: '-en', pos: 'verb', ja: '緩める' },
    { word: 'tighten',    suffix: '-en', pos: 'verb', ja: '締める' },
    // ADJECTIVES: -ful
    { word: 'beautiful',  suffix: '-ful', pos: 'adjective', ja: '美しい' },
    { word: 'careful',    suffix: '-ful', pos: 'adjective', ja: '注意深い' },
    { word: 'successful', suffix: '-ful', pos: 'adjective', ja: '成功した' },
    { word: 'powerful',   suffix: '-ful', pos: 'adjective', ja: '強力な' },
    { word: 'helpful',    suffix: '-ful', pos: 'adjective', ja: '役に立つ' },
    { word: 'harmful',    suffix: '-ful', pos: 'adjective', ja: '有害な' },
    { word: 'meaningful', suffix: '-ful', pos: 'adjective', ja: '意味のある' },
    { word: 'thoughtful', suffix: '-ful', pos: 'adjective', ja: '思慮深い' },
    { word: 'peaceful',   suffix: '-ful', pos: 'adjective', ja: '平和な' },
    { word: 'grateful',   suffix: '-ful', pos: 'adjective', ja: '感謝している' },
    // ADJECTIVES: -less
    { word: 'hopeless',   suffix: '-less', pos: 'adjective', ja: '望みのない' },
    { word: 'useless',    suffix: '-less', pos: 'adjective', ja: '役に立たない' },
    { word: 'careless',   suffix: '-less', pos: 'adjective', ja: '不注意な' },
    { word: 'helpless',   suffix: '-less', pos: 'adjective', ja: '無力な' },
    { word: 'endless',    suffix: '-less', pos: 'adjective', ja: '終わりのない' },
    { word: 'harmless',   suffix: '-less', pos: 'adjective', ja: '無害な' },
    { word: 'reckless',   suffix: '-less', pos: 'adjective', ja: '無謀な' },
    { word: 'speechless', suffix: '-less', pos: 'adjective', ja: '言葉を失った' },
    // ADJECTIVES: -ous
    { word: 'famous',    suffix: '-ous', pos: 'adjective', ja: '有名な' },
    { word: 'dangerous', suffix: '-ous', pos: 'adjective', ja: '危険な' },
    { word: 'serious',   suffix: '-ous', pos: 'adjective', ja: '深刻な' },
    { word: 'curious',   suffix: '-ous', pos: 'adjective', ja: '好奇心旺盛な' },
    { word: 'obvious',   suffix: '-ous', pos: 'adjective', ja: '明らかな' },
    { word: 'generous',  suffix: '-ous', pos: 'adjective', ja: '寛大な' },
    { word: 'various',   suffix: '-ous', pos: 'adjective', ja: '様々な' },
    { word: 'nervous',   suffix: '-ous', pos: 'adjective', ja: '緊張した' },
    { word: 'enormous',  suffix: '-ous', pos: 'adjective', ja: '巨大な' },
    { word: 'ambitious', suffix: '-ous', pos: 'adjective', ja: '野心的な' },
    { word: 'precious',  suffix: '-ous', pos: 'adjective', ja: '貴重な' },
    { word: 'numerous',  suffix: '-ous', pos: 'adjective', ja: '多数の' },
    // ADJECTIVES: -al
    { word: 'natural',      suffix: '-al', pos: 'adjective', ja: '自然な' },
    { word: 'personal',     suffix: '-al', pos: 'adjective', ja: '個人的な' },
    { word: 'professional', suffix: '-al', pos: 'adjective', ja: '専門的な' },
    { word: 'additional',   suffix: '-al', pos: 'adjective', ja: '追加の' },
    { word: 'national',     suffix: '-al', pos: 'adjective', ja: '国家の' },
    { word: 'traditional',  suffix: '-al', pos: 'adjective', ja: '伝統的な' },
    { word: 'financial',    suffix: '-al', pos: 'adjective', ja: '財務的な' },
    { word: 'original',     suffix: '-al', pos: 'adjective', ja: '独創的な' },
    { word: 'cultural',     suffix: '-al', pos: 'adjective', ja: '文化的な' },
    { word: 'digital',      suffix: '-al', pos: 'adjective', ja: 'デジタルの' },
    { word: 'global',       suffix: '-al', pos: 'adjective', ja: '世界規模の' },
    { word: 'central',      suffix: '-al', pos: 'adjective', ja: '中心的な' },
    // ADJECTIVES: -ive
    { word: 'active',        suffix: '-ive', pos: 'adjective', ja: '積極的な' },
    { word: 'creative',      suffix: '-ive', pos: 'adjective', ja: '創造的な' },
    { word: 'effective',     suffix: '-ive', pos: 'adjective', ja: '効果的な' },
    { word: 'productive',    suffix: '-ive', pos: 'adjective', ja: '生産的な' },
    { word: 'positive',      suffix: '-ive', pos: 'adjective', ja: '前向きな' },
    { word: 'sensitive',     suffix: '-ive', pos: 'adjective', ja: '敏感な' },
    { word: 'attractive',    suffix: '-ive', pos: 'adjective', ja: '魅力的な' },
    { word: 'competitive',   suffix: '-ive', pos: 'adjective', ja: '競争的な' },
    { word: 'innovative',    suffix: '-ive', pos: 'adjective', ja: '革新的な' },
    { word: 'comprehensive', suffix: '-ive', pos: 'adjective', ja: '包括的な' },
    { word: 'alternative',   suffix: '-ive', pos: 'adjective', ja: '代替の' },
    { word: 'exclusive',     suffix: '-ive', pos: 'adjective', ja: '排他的な' },
    // ADJECTIVES: -ic
    { word: 'academic',   suffix: '-ic', pos: 'adjective', ja: '学術的な' },
    { word: 'economic',   suffix: '-ic', pos: 'adjective', ja: '経済的な' },
    { word: 'specific',   suffix: '-ic', pos: 'adjective', ja: '特定の' },
    { word: 'realistic',  suffix: '-ic', pos: 'adjective', ja: '現実的な' },
    { word: 'strategic',  suffix: '-ic', pos: 'adjective', ja: '戦略的な' },
    { word: 'systematic', suffix: '-ic', pos: 'adjective', ja: '体系的な' },
    { word: 'scientific', suffix: '-ic', pos: 'adjective', ja: '科学的な' },
    { word: 'dramatic',   suffix: '-ic', pos: 'adjective', ja: '劇的な' },
    { word: 'automatic',  suffix: '-ic', pos: 'adjective', ja: '自動の' },
    // ADJECTIVES: -able / -ible
    { word: 'available',   suffix: '-able', pos: 'adjective', ja: '利用可能な' },
    { word: 'comfortable', suffix: '-able', pos: 'adjective', ja: '快適な' },
    { word: 'reasonable',  suffix: '-able', pos: 'adjective', ja: '合理的な' },
    { word: 'valuable',    suffix: '-able', pos: 'adjective', ja: '価値ある' },
    { word: 'suitable',    suffix: '-able', pos: 'adjective', ja: '適切な' },
    { word: 'reliable',    suffix: '-able', pos: 'adjective', ja: '信頼できる' },
    { word: 'sustainable', suffix: '-able', pos: 'adjective', ja: '持続可能な' },
    { word: 'remarkable',  suffix: '-able', pos: 'adjective', ja: '注目すべき' },
    { word: 'responsible', suffix: '-ible', pos: 'adjective', ja: '責任ある' },
    { word: 'possible',    suffix: '-ible', pos: 'adjective', ja: '可能な' },
    { word: 'flexible',    suffix: '-ible', pos: 'adjective', ja: '柔軟な' },
    { word: 'accessible',  suffix: '-ible', pos: 'adjective', ja: '利用しやすい' },
    // ADJECTIVES: -ant
    { word: 'important',   suffix: '-ant', pos: 'adjective', ja: '重要な' },
    { word: 'significant', suffix: '-ant', pos: 'adjective', ja: '著しい' },
    { word: 'pleasant',    suffix: '-ant', pos: 'adjective', ja: '快い' },
    { word: 'relevant',    suffix: '-ant', pos: 'adjective', ja: '関連した' },
    { word: 'brilliant',   suffix: '-ant', pos: 'adjective', ja: '優れた' },
    { word: 'dominant',    suffix: '-ant', pos: 'adjective', ja: '支配的な' },
    { word: 'constant',    suffix: '-ant', pos: 'adjective', ja: '絶え間ない' },
    { word: 'tolerant',    suffix: '-ant', pos: 'adjective', ja: '寛容な' },
    { word: 'abundant',    suffix: '-ant', pos: 'adjective', ja: '豊富な' },
    { word: 'reluctant',   suffix: '-ant', pos: 'adjective', ja: '気が進まない' },
    { word: 'resistant',   suffix: '-ant', pos: 'adjective', ja: '抵抗力のある' },
    { word: 'instant',     suffix: '-ant', pos: 'adjective', ja: '即座の' },
    // ADJECTIVES: -ent
    { word: 'different',   suffix: '-ent', pos: 'adjective', ja: '異なる' },
    { word: 'recent',      suffix: '-ent', pos: 'adjective', ja: '最近の' },
    { word: 'patient',     suffix: '-ent', pos: 'adjective', ja: '忍耐強い' },
    { word: 'efficient',   suffix: '-ent', pos: 'adjective', ja: '効率的な' },
    { word: 'confident',   suffix: '-ent', pos: 'adjective', ja: '自信のある' },
    { word: 'independent', suffix: '-ent', pos: 'adjective', ja: '独立した' },
    { word: 'competent',   suffix: '-ent', pos: 'adjective', ja: '有能な' },
    { word: 'persistent',  suffix: '-ent', pos: 'adjective', ja: '粘り強い' },
    { word: 'intelligent', suffix: '-ent', pos: 'adjective', ja: '知的な' },
    { word: 'sufficient',  suffix: '-ent', pos: 'adjective', ja: '十分な' },
    { word: 'evident',     suffix: '-ent', pos: 'adjective', ja: '明白な' },
    { word: 'urgent',      suffix: '-ent', pos: 'adjective', ja: '緊急の' },
    // ADVERBS: -ly
    { word: 'quickly',       suffix: '-ly', pos: 'adverb', ja: 'すばやく' },
    { word: 'carefully',     suffix: '-ly', pos: 'adverb', ja: '注意深く' },
    { word: 'actually',      suffix: '-ly', pos: 'adverb', ja: '実際に' },
    { word: 'approximately', suffix: '-ly', pos: 'adverb', ja: 'おおよそ' },
    { word: 'recently',      suffix: '-ly', pos: 'adverb', ja: '最近' },
    { word: 'directly',      suffix: '-ly', pos: 'adverb', ja: '直接に' },
    { word: 'finally',       suffix: '-ly', pos: 'adverb', ja: 'ついに' },
    { word: 'generally',     suffix: '-ly', pos: 'adverb', ja: '一般的に' },
    { word: 'immediately',   suffix: '-ly', pos: 'adverb', ja: '即座に' },
    { word: 'regularly',     suffix: '-ly', pos: 'adverb', ja: '定期的に' },
    { word: 'significantly', suffix: '-ly', pos: 'adverb', ja: '著しく' },
    { word: 'particularly',  suffix: '-ly', pos: 'adverb', ja: '特に' },
    { word: 'occasionally',  suffix: '-ly', pos: 'adverb', ja: '時々' },
    { word: 'frequently',    suffix: '-ly', pos: 'adverb', ja: '頻繁に' },
    { word: 'gradually',     suffix: '-ly', pos: 'adverb', ja: '徐々に' },
    { word: 'absolutely',    suffix: '-ly', pos: 'adverb', ja: '絶対に' },
    { word: 'certainly',     suffix: '-ly', pos: 'adverb', ja: '確かに' },
    { word: 'constantly',    suffix: '-ly', pos: 'adverb', ja: '常に' },
    { word: 'effectively',   suffix: '-ly', pos: 'adverb', ja: '効果的に' },
    { word: 'obviously',     suffix: '-ly', pos: 'adverb', ja: '明らかに' },
    { word: 'properly',      suffix: '-ly', pos: 'adverb', ja: '適切に' },
    { word: 'entirely',      suffix: '-ly', pos: 'adverb', ja: '完全に' },
  ];

  var IRREGULAR_WORDS = [
    // Verbs
    { word: 'launch',    suffix: '', pos: 'verb', ja: '立ち上げる' },
    { word: 'boost',     suffix: '', pos: 'verb', ja: '押し上げる' },
    { word: 'claim',     suffix: '', pos: 'verb', ja: '主張する' },
    { word: 'confirm',   suffix: '', pos: 'verb', ja: '確認する' },
    { word: 'expand',    suffix: '', pos: 'verb', ja: '拡大する' },
    { word: 'obtain',    suffix: '', pos: 'verb', ja: '得る' },
    { word: 'propose',   suffix: '', pos: 'verb', ja: '提案する' },
    { word: 'reveal',    suffix: '', pos: 'verb', ja: '明かす' },
    { word: 'submit',    suffix: '', pos: 'verb', ja: '提出する' },
    { word: 'transfer',  suffix: '', pos: 'verb', ja: '移す' },
    { word: 'pursue',    suffix: '', pos: 'verb', ja: '追求する' },
    { word: 'inspire',   suffix: '', pos: 'verb', ja: '刺激する' },
    { word: 'afford',    suffix: '', pos: 'verb', ja: '余裕がある' },
    { word: 'arrange',   suffix: '', pos: 'verb', ja: '手配する' },
    { word: 'approach',  suffix: '', pos: 'verb', ja: '取り組む' },
    { word: 'ensure',    suffix: '', pos: 'verb', ja: '確保する' },
    { word: 'implement', suffix: '', pos: 'verb', ja: '実施する' },
    { word: 'enhance',   suffix: '', pos: 'verb', ja: '高める' },
    { word: 'reflect',   suffix: '', pos: 'verb', ja: '反映する' },
    { word: 'select',    suffix: '', pos: 'verb', ja: '選ぶ' },
    // Nouns
    { word: 'access',   suffix: '', pos: 'noun', ja: 'アクセス' },
    { word: 'attempt',  suffix: '', pos: 'noun', ja: '試み' },
    { word: 'benefit',  suffix: '', pos: 'noun', ja: '利益' },
    { word: 'conflict', suffix: '', pos: 'noun', ja: '対立' },
    { word: 'demand',   suffix: '', pos: 'noun', ja: '需要' },
    { word: 'impact',   suffix: '', pos: 'noun', ja: '影響' },
    { word: 'output',   suffix: '', pos: 'noun', ja: '産出量' },
    { word: 'result',   suffix: '', pos: 'noun', ja: '結果' },
    { word: 'risk',     suffix: '', pos: 'noun', ja: 'リスク' },
    { word: 'trend',    suffix: '', pos: 'noun', ja: '傾向' },
    { word: 'budget',   suffix: '', pos: 'noun', ja: '予算' },
    { word: 'loss',     suffix: '', pos: 'noun', ja: '損失' },
    { word: 'scope',    suffix: '', pos: 'noun', ja: '範囲' },
    { word: 'task',     suffix: '', pos: 'noun', ja: '課題' },
    { word: 'proof',    suffix: '', pos: 'noun', ja: '証拠' },
    { word: 'rate',     suffix: '', pos: 'noun', ja: '割合' },
    { word: 'fund',     suffix: '', pos: 'noun', ja: '資金' },
    { word: 'stress',   suffix: '', pos: 'noun', ja: 'ストレス' },
    { word: 'peak',     suffix: '', pos: 'noun', ja: '頂点・ピーク' },
    { word: 'draft',    suffix: '', pos: 'noun', ja: '草案' },
    // Adjectives
    { word: 'brief',  suffix: '', pos: 'adjective', ja: '簡潔な' },
    { word: 'broad',  suffix: '', pos: 'adjective', ja: '広い' },
    { word: 'keen',   suffix: '', pos: 'adjective', ja: '熱心な' },
    { word: 'prompt', suffix: '', pos: 'adjective', ja: '迅速な' },
    { word: 'sharp',  suffix: '', pos: 'adjective', ja: '鋭い' },
    { word: 'smart',  suffix: '', pos: 'adjective', ja: '賢い' },
    { word: 'strict', suffix: '', pos: 'adjective', ja: '厳しい' },
    { word: 'tight',  suffix: '', pos: 'adjective', ja: '厳しい・窮屈な' },
    { word: 'vast',   suffix: '', pos: 'adjective', ja: '広大な' },
    { word: 'bold',   suffix: '', pos: 'adjective', ja: '大胆な' },
    { word: 'mild',   suffix: '', pos: 'adjective', ja: '穏やかな' },
    { word: 'prime',  suffix: '', pos: 'adjective', ja: '主要な' },
    { word: 'rough',  suffix: '', pos: 'adjective', ja: '荒い' },
    { word: 'tough',  suffix: '', pos: 'adjective', ja: '困難な' },
    { word: 'vague',  suffix: '', pos: 'adjective', ja: '曖昧な' },
    { word: 'fair',   suffix: '', pos: 'adjective', ja: '公平な' },
    { word: 'raw',    suffix: '', pos: 'adjective', ja: '未加工の' },
    { word: 'spare',  suffix: '', pos: 'adjective', ja: '余分の' },
    { word: 'prone',  suffix: '', pos: 'adjective', ja: '〜しがちな' },
    { word: 'sole',   suffix: '', pos: 'adjective', ja: '唯一の' },
    // Adverbs (non -ly)
    { word: 'well',   suffix: '', pos: 'adverb', ja: 'うまく・よく' },
    { word: 'hard',   suffix: '', pos: 'adverb', ja: '懸命に' },
    { word: 'fast',   suffix: '', pos: 'adverb', ja: '速く' },
    { word: 'quite',  suffix: '', pos: 'adverb', ja: 'かなり' },
    { word: 'still',  suffix: '', pos: 'adverb', ja: 'まだ' },
    { word: 'rather', suffix: '', pos: 'adverb', ja: 'むしろ' },
    { word: 'indeed', suffix: '', pos: 'adverb', ja: '確かに' },
    { word: 'just',   suffix: '', pos: 'adverb', ja: 'ちょうど・ただ' },
  ];

  return {
    POS: POS,
    CHOICES: CHOICES,
    REGULAR_WORDS: REGULAR_WORDS,
    IRREGULAR_WORDS: IRREGULAR_WORDS,
  };
})();
